# Temperament (音律)

* [Pythagorean tuning - Wikipedia](https://en.wikipedia.org/wiki/Pythagorean_tuning)
    - [Pythagorean interval - Wikipedia](https://en.wikipedia.org/wiki/Pythagorean_interval)

In [16]:
%%ai_ask
ピタゴラス音律について

ピタゴラス音律は、古代ギリシャの哲学者ピタゴラスが提唱した音楽理論で、音程の比率を整数で表現する方法です。具体的には、オクターブの上下で周波数比が2:1、完全5度の音程で3:2、完全4度の音程で4:3となるように調律されます。この理論は、西洋音楽の基礎となっています。

In [18]:
%%ai_continue
ピタゴラス音律と、音階や和音との関係について

ピタゴラス音律は、音程の比率を整数で表現する方法であり、西洋音楽の基礎となっています。この音律に基づいて、音階や和音が構成されます。

例えば、Cメジャースケールは、ピタゴラス音律に基づいて構成されています。Cメジャースケールは、C、D、E、F、G、A、Bの7つの音から成り、隣り合う音の周波数比は、ピタゴラス音律によれば、2:1、9:8、81:64、4:3、3:2、27:16、243:128となります。

また、和音においても、ピタゴラス音律に基づいた調律が行われます。例えば、Cメジャーコードは、C、E、Gの3つの音から構成され、隣り合う音の周波数比は、ピタゴラス音律によれば、4:5:6となります。

つまり、ピタゴラス音律は、音階や和音の構成に大きく関わっており、西洋音楽の基礎となっていると言えます。

## Pythagorean method

ピタゴラスは次の式を満たす $m, n \geq 0 $ を探して $7$ 音階を定めた:

$$ 1 \leq \left( \frac{3}{2} \right)^m \times \left( \frac{1}{2} \right)^{n} \leq 2$$
または
$$ 1 \leq \left( \frac{2}{3} \right)^m \times 2^n \leq 2$$

例えば

$$\left( \frac{2}{3} \right)^1 \times 2^1 = \frac{4}{3}$$

$$\left(\frac{3}{2} \right)^4 \times \left( \frac{1}{2} \right)^2 = \frac{3^4}{2^6} = \frac{81}{64} = 1.265625 \approx 1.25 = \frac{5}{4}$$

C, E, Gの比を求める:

$$ 1 : \frac{81}{64} : \frac{3}{2} \approx 1 : \frac{5}{4} : \frac{3}{2} = \frac{4}{4} : \frac{5}{4} : \frac{6}{4} = 4 : 5 : 6$$

In [2]:
from fractions import Fraction
import numpy as np

In [5]:
# 0から4までの配列
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
# 3/2の冪乗を列挙する
(3/2)**np.arange(5)

array([1.    , 1.5   , 2.25  , 3.375 , 5.0625])

In [9]:
# 3/2の4乗を繰り返し2で割る
((3/2)**4)*((1/2)**np.arange(6))

array([5.0625    , 2.53125   , 1.265625  , 0.6328125 , 0.31640625,
       0.15820312])

In [12]:
# 3番目が求める数 (繰り返し2で割って2より小さくなる最初の数)
((3/2)**4)*((1/2)**np.arange(6)) < 2.0

array([False, False,  True,  True,  True,  True])

* [numpy.argmax — NumPy v1.24 Manual](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

In [13]:
# numpy argmaxを使うと配列の添字を得られる
np.argmax(((3/2)**4)*((1/2)**np.arange(6)) < 2.0)

2

In [15]:
((3/2)**4)*((1/2)**np.arange(6))[2]

1.265625

In [24]:
# 重複する参照を変数に置き換えてプロウグラムっぽく書き直す
x = ((3/2)**4)*((1/2)**np.arange(6))
x[np.argmax(x < 2.0)]

1.265625

In [27]:
# 有理数 (有限小数) なので分数表示する
Fraction((3/2)**4 * (1/2)**2)

Fraction(81, 64)

In [28]:
# 分母が10以下の近似を求める
Fraction((3/2)**4 * (1/2)**2).limit_denominator(10)

Fraction(5, 4)

In [23]:
5 / 4

1.25

## 3/2倍系列

In [36]:
# 二重ループで探索する
for m in np.arange(5):
    for n in np.arange(6):
        x = (3/2)**m * (1/2)**n
        if x < 2.0:
            print(m, n, x, Fraction(x))
            break

0 0 1.0 1
1 0 1.5 3/2
2 1 1.125 9/8
3 1 1.6875 27/16
4 2 1.265625 81/64


## 2/3倍系列

In [40]:
# 二重ループで探索する
for m in np.arange(5):
    for n in np.arange(6):
        x = (2/3)**m * (2)**n
        if x > 1.0:
            print(m, n, x, Fraction(x).limit_denominator(10))
            break

0 1 2.0 2
1 1 1.3333333333333333 4/3
2 2 1.7777777777777777 16/9
3 2 1.185185185185185 6/5
4 3 1.5802469135802466 11/7


## 現在使われている平均律との差

In [55]:
import pandas as pd

In [170]:
dfs = pd.read_html('https://en.wikipedia.org/wiki/Pythagorean_tuning')
dfs[0]

Note   Interval from D  Formula   =  =.1  Frequency ratio  Size (cents)  \
0    A♭  diminished fifth      NaN NaN  NaN              NaN        588.27   
1    E♭      minor second      NaN NaN  NaN              NaN         90.22   
2    B♭       minor sixth      NaN NaN  NaN              NaN        792.18   
3     F       minor third      NaN NaN  NaN              NaN        294.13   
4     C     minor seventh      NaN NaN  NaN              NaN        996.09   
5     G    perfect fourth      NaN NaN  NaN              NaN        498.04   
6     D            unison      NaN NaN  NaN              NaN          0.00   
7     A     perfect fifth      NaN NaN  NaN              NaN        701.96   
8     E      major second      NaN NaN  NaN              NaN        203.91   
9     B       major sixth      NaN NaN  NaN              NaN        905.87   
10   F♯       major third      NaN NaN  NaN              NaN        407.82   
11   C♯     major seventh      NaN NaN  NaN              NaN       1109.78   
12   G♯  augmented fourth      NaN NaN  NaN              NaN        611.73   

   12-TET-dif (cents)  
0              −11.73  
1               −9.78  
2               −7.82  
3               −5.87  
4               −3.91  
5               −1.96  
6                0.00  
7                1.96  
8                3.91  
9                5.87  
10               7.82  
11               9.78  
12              11.73